version: '3.8'

services:
  web:
    build:
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=postgresql+psycopg://test:test@db:5432/testtaskwb
    ports:
      - 8000:8000
    depends_on:
      - db
    networks:
      - default

  db:
    image: postgres:16-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=testtaskwb
    ports:
      - 5432:5432
    networks:
      - default

networks:
  default:
    driver: bridge



volumes:
  postgres_data: